// AUTO-GENERATED by scripts/gen_portal_header.py — do not edit directly.
// Source: accesspoint/captiveportal.html
#pragma once
const char PORTAL_HTML[] PROGMEM = R"EOF(
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Lumatron WiFi Setup</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      background: #121212;
      color: #e0e0e0;
      font-family: sans-serif;
      font-size: 16px;
      display: flex;
      flex-direction: column;
      align-items: center;
      min-height: 100vh;
      padding: 2rem 1rem;
    }
    h1 { font-size: 2rem; margin-bottom: 0.25rem; color: #fff; }
    #orb-info { color: #888; font-size: 0.85rem; margin-bottom: 2rem; }
    .card {
      background: #1e1e1e;
      border-radius: 12px;
      padding: 1.5rem;
      width: 100%;
      max-width: 420px;
      margin-bottom: 1rem;
    }
    .card h2 { font-size: 1rem; color: #aaa; margin-bottom: 0.75rem; display: flex; justify-content: space-between; align-items: center; }
    #network-list { list-style: none; }
    #network-list li {
      padding: 0.6rem 0.75rem;
      border-radius: 8px;
      cursor: pointer;
      display: flex;
      justify-content: space-between;
      align-items: center;
      transition: background 0.15s;
    }
    #network-list li:hover { background: #2a2a2a; }
    #network-list li.selected { background: #2a3a2a; }
    .signal { font-size: 0.75rem; color: #666; }
    #scan-status { color: #666; font-size: 0.85rem; font-style: italic; }
    label { display: block; font-size: 0.85rem; color: #aaa; margin-bottom: 0.25rem; margin-top: 1rem; }
    input[type=text], input[type=password] {
      width: 100%;
      padding: 0.6rem 0.75rem;
      border-radius: 8px;
      border: 1px solid #333;
      background: #2a2a2a;
      color: #e0e0e0;
      font-size: 1rem;
    }
    input:focus { outline: none; border-color: #555; }
    .show-pw {
      display: flex;
      align-items: center;
      gap: 0.5rem;
      margin-top: 0.5rem;
      font-size: 0.85rem;
      color: #888;
      cursor: pointer;
      user-select: none;
    }
    .btn {
      display: block;
      width: 100%;
      padding: 0.75rem;
      margin-top: 1.25rem;
      border-radius: 8px;
      border: none;
      background: #3a7a3a;
      color: #fff;
      font-size: 1rem;
      cursor: pointer;
      transition: background 0.15s;
    }
    .btn:hover { background: #4a9a4a; }
    .btn:disabled { background: #333; color: #666; cursor: default; }
    .btn-sm {
      background: none;
      border: 1px solid #444;
      color: #aaa;
      font-size: 0.75rem;
      padding: 0.2rem 0.6rem;
      border-radius: 6px;
      cursor: pointer;
    }
    .btn-sm:hover { border-color: #666; color: #ccc; }
    #status {
      margin-top: 0.75rem;
      font-size: 0.9rem;
      min-height: 1.2em;
      text-align: center;
    }
    .status-ok { color: #5a5; }
    .status-err { color: #a55; }
    .status-info { color: #88a; }
  </style>
</head>
<body>
  <h1>Lumatron WiFi Setup</h1>
  <div id="orb-info">Loading...</div>

  <div class="card">
    <h2>
      Networks
      <button class="btn-sm" id="refresh-btn" onclick="doScan()">Refresh</button>
    </h2>
    <ul id="network-list"><li id="scan-status">Scanning...</li></ul>
  </div>

  <div class="card">
    <label for="ssid">SSID</label>
    <input type="text" id="ssid" placeholder="Network name" autocomplete="off" autocorrect="off" autocapitalize="none" spellcheck="false"/>
    <label for="password">Password</label>
    <input type="password" id="password" placeholder="Leave blank if open"/>
    <label class="show-pw">
      <input type="checkbox" id="show-pw" onchange="togglePw()"/> Show password
    </label>
    <button class="btn" id="connect-btn" onclick="doConnect()">Connect</button>
    <div id="status"></div>
  </div>

  <script>
    const ssidInput = document.getElementById('ssid')
    const pwInput = document.getElementById('password')
    const connectBtn = document.getElementById('connect-btn')
    const statusEl = document.getElementById('status')

    async function loadInfo() {
      try {
        const r = await fetch('/info')
        const d = await r.json()
        document.getElementById('orb-info').textContent =
          (d.orbID ? 'Orb: ' + d.orbID : '') +
          (d.version ? '  ·  Firmware v' + d.version : '')
      } catch(e) {
        document.getElementById('orb-info').textContent = ''
      }
    }

    async function doScan() {
      const list = document.getElementById('network-list')
      list.innerHTML = '<li id="scan-status">Scanning...</li>'
      document.getElementById('refresh-btn').disabled = true
      try {
        const r = await fetch('/scan')
        const nets = await r.json()
        renderNetworks(nets)
      } catch(e) {
        list.innerHTML = '<li id="scan-status">Scan failed</li>'
      }
      document.getElementById('refresh-btn').disabled = false
    }

    function renderNetworks(nets) {
      const list = document.getElementById('network-list')
      if (!nets || nets.length === 0) {
        list.innerHTML = '<li id="scan-status">No networks found</li>'
        return
      }
      list.innerHTML = ''
      nets.forEach(n => {
        const li = document.createElement('li')
        const bars = signalBars(n.rssi)
        li.innerHTML = '<span>' + escHtml(n.ssid) + (n.open ? '' : ' 🔒') + '</span><span class="signal">' + bars + ' ' + n.rssi + ' dBm</span>'
        li.onclick = () => {
          document.querySelectorAll('#network-list li').forEach(x => x.classList.remove('selected'))
          li.classList.add('selected')
          ssidInput.value = n.ssid
          pwInput.focus()
        }
        list.appendChild(li)
      })
    }

    function signalBars(rssi) {
      if (rssi >= -55) return '▂▄▆█'
      if (rssi >= -67) return '▂▄▆_'
      if (rssi >= -78) return '▂▄__'
      return '▂___'
    }

    function escHtml(s) {
      return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')
    }

    function togglePw() {
      pwInput.type = document.getElementById('show-pw').checked ? 'text' : 'password'
    }

    async function doConnect() {
      const ssid = ssidInput.value.trim()
      if (!ssid) { setStatus('Enter an SSID', 'err'); return }
      connectBtn.disabled = true
      setStatus('Connecting…', 'info')
      try {
        const r = await fetch('/connect', {
          method: 'POST',
          headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
          body: 'ssid=' + encodeURIComponent(ssid) + '&password=' + encodeURIComponent(pwInput.value)
        })
        const d = await r.json()
        if (d.success) {
          setStatus('Connected! IP: ' + d.ip + '. You can close this page.', 'ok')
        } else {
          setStatus('Failed to connect. Check credentials.', 'err')
          connectBtn.disabled = false
        }
      } catch(e) {
        setStatus('Request failed. Try again.', 'err')
        connectBtn.disabled = false
      }
    }

    function setStatus(msg, type) {
      statusEl.textContent = msg
      statusEl.className = 'status-' + (type || 'info')
    }

    loadInfo()
    doScan()
  </script>
</body>
</html>
)EOF";
