#!/usr/bin/env python3
"""Generate arduino/esp32/portal_html.h from accesspoint/captiveportal.html.

Usage: python3 scripts/gen_portal_header.py
Run from the repo root.
"""
import os, sys

src = os.path.join(os.path.dirname(__file__), '..', 'accesspoint', 'captiveportal.html')
dst = os.path.join(os.path.dirname(__file__), '..', 'arduino', 'esp32', 'portal_html.h')

with open(src, 'r', encoding='utf-8') as f:
    html = f.read()

# Escape any occurrence of )EOF" inside the HTML (shouldn't exist, but be safe)
if ')EOF"' in html:
    print("ERROR: HTML contains )EOF\" which would break the raw string literal.", file=sys.stderr)
    sys.exit(1)

header = f"""// AUTO-GENERATED by scripts/gen_portal_header.py — do not edit directly.
// Source: accesspoint/captiveportal.html
#pragma once
const char PORTAL_HTML[] PROGMEM = R"EOF(
{html})EOF";
"""

with open(dst, 'w', encoding='utf-8') as f:
    f.write(header)

print(f"Written {len(html)} bytes of HTML to {dst}")
